apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-template-sample
  namespace: {{ .Values.mynamespace }}
  labels:
    {{- include "hello-helm-work.labels" . | nindent 4 }}
    drink: {{ .Values.favorite.drink | quote }}
    station: {{ .Values.favorite.station | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello-helm-work.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hello-helm-work.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-helm-work.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "nginx:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
